services:
  - type: web
    name: ice-site
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: NEXT_PUBLIC_IMGUR_CLIENT_ID
        sync: false
      - key: NEXT_PUBLIC_IMGUR_CLIENT_SECRET
        sync: false
    autoDeploy: true 